### ISSUE TITLE
browser.savescreen is not defined.

### ISSUE THREAD

**Issue by cnuk4u** [wswebcreation/wdio-image-comparison-service#44]
> **NOTE: Be aware of the fact that this module is only a plugin that provides all functionality from [`webdriver-image-comparison`](https://github.com/wswebcreation/webdriver-image-comparison). So please check if this is an issue with this plugin or with `webdriver-image-comparison`.**

**Environment (please complete the following information):**
 - Node.js version: 12.18.0
 - NPM version: 6.14.4
 - Browser name and version: chrome 83
 - Platform name and version: windows 10
 - WebdriverIO version: 6.0.5
 - wdio-image-comparison-service version: 1.13.6

**Config of WebdriverIO + wdio-image-comparison-service**

```js
services: [['image-comparison',
        // The options
        {
            // Some options, see the docs for more
            baselineFolder: './master',
            formatImageName: '{tag}-{logName}-{width}x{height}',
            screenshotPath: '/.tmp/',
            savePerInstance: true,
            autoSaveBaseline: true,
            blockOutStatusBar: true,
            blockOutToolBar: true,
            // NOTE: When you are testing a hybrid app please use this setting
            //isHybridApp: true,
            // Options for the tabbing image
            tabbableOptions:{
                circle:{
                    size: 18,
                    fontSize: 18,
                    // ...
                },
                line:{
                    color: '#ff221a', // hex-code or for example words like `red|black|green`
                    width: 3,
                },
            }
            // ... more options
        }]
    ],
```

**Describe the bug**
getting error whule "TypeError: browser.saveScreen is not a function" while using browser.saveScreen

**To Reproduce**
use browser.saveScreen method

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**

**Additional context**
![Capture](https://user-images.githubusercontent.com/34564597/84467788-c21f6580-ac9a-11ea-8429-34a7e4cba1ca.PNG)

**Comment by wswebcreation** [comment]
@cnuk4u 

Thanks for filing the issue, but can you provide **your** configuration file, based on the above mentioned implementation, from the docs, it should work. It could be that you are overwriting the services somewhere else.
Also please post the logs of WebdriverIO when you start a test, when you run it with `logLevel: 'debug'` I only need the first few log lines before the session is created on the machine

**Comment by cnuk4u** [comment]
@wswebcreation 

PFA logs as below,

2020-06-18T10:07:45.942Z DEBUG @wdio/utils:initialiseServices: initialise service "image-comparison" as NPM package
2020-06-18T10:07:46.000Z ERROR @wdio/utils:initialiseServices: Error: Couldn't initialise "wdio-image-comparison-service".
Error: The specified module could not be found.
\\?\e:\Automation\jasmine-boilerplate-master\node_modules\canvas\build\Release\canvas.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (e:\Automation\jasmine-boilerplate-master\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at safeRequire (e:\Automation\jasmine-boilerplate-master\node_modules\@wdio\utils\build\utils.js:141:11)
    at initialisePlugin (e:\Automation\jasmine-boilerplate-master\node_modules\@wdio\utils\build\initialisePlugin.js:26:41)
    at initialiseServices (e:\Automation\jasmine-boilerplate-master\node_modules\@wdio\utils\build\initialiseServices.js:34:51)
    at initialiseLauncherService (e:\Automation\jasmine-boilerplate-master\node_modules\@wdio\utils\build\initialiseServices.js:50:22)
    at Launcher.run (e:\Automation\jasmine-boilerplate-master\node_modules\@wdio\cli\build\launcher.js:73:48)
    at launch (e:\Automation\jasmine-boilerplate-master\node_modules\@wdio\cli\build\commands\run.js:138:19)
    at handler (e:\Automation\jasmine-boilerplate-master\node_modules\@wdio\cli\build\commands\run.js:171:12)
    at Object.run (e:\Automation\jasmine-boilerplate-master\node_modules\@wdio\cli\build\index.js:47:29)
    at Object.<anonymous> (e:\Automation\jasmine-boilerplate-master\node_modules\@wdio\cli\bin\wdio.js:11:21)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)

**Comment by wswebcreation** [comment]
@cnuk4u 

The logs say that the module could not be found, did you install it?

**Comment by cnuk4u** [comment]
@wswebcreation 

Issue resolved after referring to [this issue](https://github.com/Automattic/node-canvas/issues/1000)

Thanks
