### ISSUE TITLE
Got `stale element reference` error when use checkElement function

### ISSUE THREAD

**Issue by Curt900701** [wswebcreation/wdio-image-comparison-service#72]
**Environment (please complete the following information):**
 - Node.js version: 14.17.3
 - NPM version: 6.14.13
 - Browser name and version: 93.0.4577.63 (arm64)
 - Platform name and version: MAC OS 11.5 (APPLE M1)
 - WebdriverIO version: 7.9.1
 - wdio-image-comparison-service version: 7.2.0

**Describe the bug**
```
await browser.url('http://www.baidu.com')
await browser.checkElement($('#kw'), 'baidu', { /* some options */ })
```
Got error in checkElement function

**To Reproduce**
For more detail, please refer to project below:
https://github.com/Curt900701/issues_image-camparison

And run with command `npm run test`

**Log**
```
> @ test /Users/dongyang/Project/github/issues_image-camparison
> npx wdio run wdio.conf.js


Execution of 1 workers started at 2021-09-17T13:36:02.950Z

2021-09-17T13:36:06.829Z INFO @wdio/cli:launcher: Run onPrepare hook
2021-09-17T13:36:06.833Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2021-09-17T13:36:06.835Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,wdio.conf.js
[0-0] 2021-09-17T13:36:07.223Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - /cases/test.js
[0-0] 2021-09-17T13:36:07.447Z INFO devtools:puppeteer: Initiate new session using the DevTools protocol
[0-0] 2021-09-17T13:36:07.449Z INFO devtools: Launch Google Chrome with flags: --enable-automation --disable-popup-blocking --disable-extensions --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --no-default-browser-check --disable-hang-monitor --disable-prompt-on-repost --disable-client-side-phishing-detection --password-store=basic --use-mock-keychain --disable-component-extensions-with-background-pages --disable-breakpad --disable-dev-shm-usage --disable-ipc-flooding-protection --disable-renderer-backgrounding --force-fieldtrials=*BackgroundTracing/default/ --enable-features=NetworkService,NetworkServiceInProcess --disable-features=site-per-process,TranslateUI,BlinkGenPropertyTrees --window-position=0,0 --window-size=1200,900 --window-size=1920,1080
[0-0] 2021-09-17T13:36:09.554Z INFO devtools: Connect Puppeteer with browser on port 51554
[0-0] 2021-09-17T13:36:10.534Z INFO wdio-image-comparison-service: Adding commands to global browser
[0-0] 2021-09-17T13:36:10.553Z INFO devtools: COMMAND navigateTo("http://www.baidu.com/")
[0-0] 2021-09-17T13:36:11.968Z INFO devtools: RESULT null
[0-0] 2021-09-17T13:36:11.969Z INFO webdriver: COMMAND checkElement(<object>, "baidu", <object>)
[0-0] 2021-09-17T13:36:12.043Z INFO devtools: COMMAND findElement("css selector", "#kw")
[0-0] 2021-09-17T13:36:12.044Z INFO devtools: COMMAND executeScript(<fn>, <object>)
[0-0] 2021-09-17T13:36:12.086Z INFO devtools: RESULT { 'element-6066-11e4-a52e-4f735466cecf': 'ELEMENT-1' }
[0-0] 2021-09-17T13:36:12.127Z INFO devtools: COMMAND executeScript(<fn>, <object>)
[0-0] 2021-09-17T13:36:12.140Z INFO devtools: RESULT {
[0-0]   dimensions: {
[0-0]     body: { scrollHeight: 688, offsetHeight: 688 },
[0-0]     html: {
[0-0]       clientHeight: 688,
[0-0]       clientWidth: 1440,
[0-0]       scrollHeight: 688,
[0-0]       scrollWidth: 1440,
[0-0]       offsetHeight: 688
[0-0]     },
[0-0]     window: {
[0-0]       innerWidth: 1440,
[0-0]       innerHeight: 688,
[0-0]       outerHeight: 811,
[0-0]       outerWidth: 1440,
[0-0]       devicePixelRatio: 2,
[0-0]       screenWidth: 1440,
[0-0]       screenHeight: 900
[0-0]     }
[0-0]   }
[0-0] }
[0-0] 2021-09-17T13:36:12.143Z INFO devtools: COMMAND takeScreenshot()
[0-0] 2021-09-17T13:36:12.451Z INFO devtools: RESULT iVBORw0KGgoAAAANSUhEUgAAC0AAAAVcCAYAAACvZBvdAAABKmlDQ1BTa2lhA...
[0-0] 2021-09-17T13:36:12.454Z INFO devtools: COMMAND executeScript(<fn>, <object>)
[0-0] stale element reference in "tests should be OK"
stale element reference: The element with reference (...args) => target.then(async (elem) => {
                    if (!elem) {
                        let errMsg = 'Element could not be found';
                        const prevElem = await promise;
                        if (Array.isArray(prevElem) && prevInnerArgs && prevInnerArgs.prop === 'get') {
                            errMsg = `Index out of bounds! $$(${prevInnerArgs.args[0]}) returned only ${prevElem.length} elements.`;
                        }
                        throw new Error(errMsg);
                    }
                    return elem[prop](...args);
                }) is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
stale element reference: stale element reference: The element with reference (...args) => target.then(async (elem) => {
                    if (!elem) {
                        let errMsg = 'Element could not be found';
                        const prevElem = await promise;
                        if (Array.isArray(prevElem) && prevInnerArgs && prevInnerArgs.prop === 'get') {
                            errMsg = `Index out of bounds! $$(${prevInnerArgs.args[0]}) returned only ${prevElem.length} elements.`;
                        }
                        throw new Error(errMsg);
                    }
                    return elem[prop](...args);
                }) is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
    at getStaleElementError (/Users/dongyang/Project/github/issues_image-camparison/node_modules/devtools/build/utils.js:183:19)
    at /Users/dongyang/Project/github/issues_image-camparison/node_modules/devtools/build/utils.js:156:23
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)
[0-0] 2021-09-17T13:36:12.464Z INFO devtools: COMMAND deleteSession()
[0-0] 2021-09-17T13:36:12.465Z INFO devtools: RESULT null
[0-0] FAILED in chrome - /cases/test.js
2021-09-17T13:36:12.601Z INFO @wdio/cli:launcher: Run onComplete hook

 "spec" Reporter:
------------------------------------------------------------------
[Chrome 93.0.4577.82 darwin #0-0] Running: Chrome (v93.0.4577.82) on darwin
[Chrome 93.0.4577.82 darwin #0-0] Session ID: 450a2f5a-6554-49ed-9aa9-84a14477c17c
[Chrome 93.0.4577.82 darwin #0-0]
[Chrome 93.0.4577.82 darwin #0-0] » /cases/test.js
[Chrome 93.0.4577.82 darwin #0-0] tests
[Chrome 93.0.4577.82 darwin #0-0]    ✖ should be OK
[Chrome 93.0.4577.82 darwin #0-0]
[Chrome 93.0.4577.82 darwin #0-0] 1 failing (1.9s)
[Chrome 93.0.4577.82 darwin #0-0]
[Chrome 93.0.4577.82 darwin #0-0] 1) tests should be OK
[Chrome 93.0.4577.82 darwin #0-0] stale element reference: The element with reference (...args) => target.then(async (elem) => {
                    if (!elem) {
                        let errMsg = 'Element could not be found';
                        const prevElem = await promise;
                        if (Array.isArray(prevElem) && prevInnerArgs && prevInnerArgs.prop === 'get') {
                            errMsg = `Index out of bounds! $$(${prevInnerArgs.args[0]}) returned only ${prevElem.length} elements.`;
                        }
                        throw new Error(errMsg);
                    }
                    return elem[prop](...args);
                }) is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
[Chrome 93.0.4577.82 darwin #0-0] stale element reference: The element with reference (...args) => target.then(async (elem) => {
[Chrome 93.0.4577.82 darwin #0-0]                     if (!elem) {
[Chrome 93.0.4577.82 darwin #0-0]                         let errMsg = 'Element could not be found';
[Chrome 93.0.4577.82 darwin #0-0]                         const prevElem = await promise;
[Chrome 93.0.4577.82 darwin #0-0]                         if (Array.isArray(prevElem) && prevInnerArgs && prevInnerArgs.prop === 'get') {
[Chrome 93.0.4577.82 darwin #0-0]                             errMsg = `Index out of bounds! $$(${prevInnerArgs.args[0]}) returned only ${prevElem.length} elements.`;
[Chrome 93.0.4577.82 darwin #0-0]                         }
[Chrome 93.0.4577.82 darwin #0-0]                         throw new Error(errMsg);
[Chrome 93.0.4577.82 darwin #0-0]                     }
[Chrome 93.0.4577.82 darwin #0-0]                     return elem[prop](...args);
[Chrome 93.0.4577.82 darwin #0-0]                 }) is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
[Chrome 93.0.4577.82 darwin #0-0] stale element reference: stale element reference: The element with reference (...args) => target.then(async (elem) => {
[Chrome 93.0.4577.82 darwin #0-0]                     if (!elem) {
[Chrome 93.0.4577.82 darwin #0-0]                         let errMsg = 'Element could not be found';
[Chrome 93.0.4577.82 darwin #0-0]                         const prevElem = await promise;
[Chrome 93.0.4577.82 darwin #0-0]                         if (Array.isArray(prevElem) && prevInnerArgs && prevInnerArgs.prop === 'get') {
[Chrome 93.0.4577.82 darwin #0-0]                             errMsg = `Index out of bounds! $$(${prevInnerArgs.args[0]}) returned only ${prevElem.length} elements.`;
[Chrome 93.0.4577.82 darwin #0-0]                         }
[Chrome 93.0.4577.82 darwin #0-0]                         throw new Error(errMsg);
[Chrome 93.0.4577.82 darwin #0-0]                     }
[Chrome 93.0.4577.82 darwin #0-0]                     return elem[prop](...args);
[Chrome 93.0.4577.82 darwin #0-0]                 }) is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
[Chrome 93.0.4577.82 darwin #0-0]     at getStaleElementError (/Users/dongyang/Project/github/issues_image-camparison/node_modules/devtools/build/utils.js:183:19)
[Chrome 93.0.4577.82 darwin #0-0]     at /Users/dongyang/Project/github/issues_image-camparison/node_modules/devtools/build/utils.js:156:23
[Chrome 93.0.4577.82 darwin #0-0]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[Chrome 93.0.4577.82 darwin #0-0]     at async Promise.all (index 0)


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:09 

2021-09-17T13:36:12.602Z INFO @wdio/local-runner: Shutting down spawned worker
2021-09-17T13:36:12.856Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2021-09-17T13:36:12.857Z INFO @wdio/local-runner: shutting down
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ test: `npx wdio run wdio.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Curt900701** [comment]
@wswebcreation Could you kindly help to confirm?

**Comment by opensourcesensor** [comment]
Hi @Curt900701 ,
if you use async mode you have to give an await to variables.

Try:
await browser.checkElement(**await** $('#kw'), 'baidu', { /* some options */ })

Does this help?
BR
Fabian Schmider

**Comment by Curt900701** [comment]
@opensourcesensor 
Yes, that works now.
Thank you for the confirmation.

Please let me close the issue.

**Comment by wswebcreation** [comment]
Thanks @opensourcesensor for helping out with this
