### ISSUE TITLE
Seeing an Error on build after moving to Nodev14 in our Jenkins pipeline

### ISSUE THREAD

**Issue by wbigno** [wswebcreation/wdio-image-comparison-service#84]
Seeing error in our log on every build in Jenkins, does not occur locally
```log
2022-03-23T19:19:10.252Z INFO @wdio/local-runner: Run worker command: run
2022-03-23T19:19:10.446Z DEBUG @wdio/config:utils: Found '@babel/register' package, auto-compiling files with Babel
2022-03-23T19:19:11.341Z DEBUG @wdio/local-runner:utils: init remote session
2022-03-23T19:19:11.349Z DEBUG @wdio/utils:initialiseServices: initialise service "sauce" as NPM package
2022-03-23T19:19:11.600Z DEBUG @wdio/utils:initialiseServices: initialise service "image-comparison" as NPM package
2022-03-23T19:19:11.668Z ERROR @wdio/utils:initialiseServices: Error: Couldn't initialise "wdio-image-comparison-service".
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/canvas/build/Release/canvas.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader [as .js] (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/pirates/lib/index.js:141:7)
    at safeRequire (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/@wdio/utils/build/utils.js:187:15)
    at initialisePlugin (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/@wdio/utils/build/initialisePlugin.js:37:44)
    at initialiseServices (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/@wdio/utils/build/initialiseServices.js:59:56)
    at initialiseWorkerService (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/@wdio/utils/build/initialiseServices.js:140:26)
    at Runner.run (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/@wdio/runner/build/index.js:75:45)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
**If it's about a specific piece of code, try and include some of it to support your question.**
[...]

**Environment (please complete the following information):**
```json
 "devDependencies": {
    "@babel/cli": "^7.17.6",
    "@babel/core": "^7.17.5",
    "@babel/preset-env": "^7.16.11",
    "@babel/register": "^7.17.0",
    "@babel/eslint-parser": "^7.17.0",
    "@wdio/allure-reporter": "^7.17.3",
    "@wdio/cli": "^7.17.4",
    "@wdio/devtools-service": "^7.17.4",
    "@wdio/junit-reporter": "^7.17.3",
    "@wdio/local-runner": "^7.17.4",
    "@wdio/mocha-framework": "^7.17.3",
    "@wdio/sauce-service": "^7.17.4",
    "@wdio/spec-reporter": "^7.17.3",
    "@wdio/sync": "^7.17.4",
    "wdio-image-comparison-service": "^1.13.6",
    "webdriverio": "^6.4.0",
    "allure-commandline": "^2.13.0",
    "chai": "^4.2.0",
    "chai-html": "^1.3.0",
    "chai-match-pattern": "^1.2.0",
    "chromedriver": "^99.0.0",
    "eslint": "^8.10.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-babel": "^5.3.1",
    "eslint-plugin-mocha": "^6.3.0",
    "global-agent": "^2.1.12",
    "request-promise": "^4.2.6",
    "request": "^2.34.0",
    "request-promise-core": "^1.1.4",
    "xml2js": "^0.4.23"
  }
```
**Additional context**

**Comment by wswebcreation** [comment]
Can you provide the platform you're running on with Jenkins. It seems that the canvas library doesn't support it and to be sure how I need to fix it, I need to know more details about your Jenkins environment

**Comment by wbigno** [comment]
Here the details requested that my server team provided to me today 
cat /etc/redhat-release Red Hat Enterprise Linux Server release 7.9 (Maipo) + uname -a Linux if21p01js 3.10.0-1160.36.2.el7.x86_64 #1 SMP Thu Jul 8 02:53:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux + npm -v 6.14.13 + node --version v14.17.3

We are using Red Hat Enterprise Linux Server release 7.9 (Maipo) 

if21p01js 3.10.0-1160.36.2.el7.x86_64 #1 SMP Thu Jul 8 02:53:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 
Our server team asked if this can run on RHEL 7?

**Comment by wswebcreation** [comment]
Hmm, I think this is an environmental issue, can you share the logs of the installation of the node modules? If the environment is not supported there should also be an error during the installation.

I'll update the canvas lib this week

**Comment by wbigno** [comment]
Here is the log, I dont see any issues with the overall install of the node modules, thanks
[log.txt](https://github.com/wswebcreation/wdio-image-comparison-service/files/8362455/log.txt)
.

**Comment by gulatirajat** [comment]
Same error while trying to run the suite from a docker container. No issue during local execution.
Installation setup during docker build:
RUN npm i \
    @babel/cli@7.17.6 \
    @babel/core@7.16.7 \
    @babel/plugin-transform-runtime@7.16.8 \
    @babel/preset-env@7.16.8 \
    @babel/preset-react@7.16.7 \
    @babel/register@7.16.9 \
    babel-plugin-module-resolver@4.1.0 \
    babel-plugin-styled-components@2.0.6 \
    @wdio/browserstack-service@^7.16.16 \
    @wdio/cli@^7.16.16 \
    @wdio/cucumber-framework@^7.16.14 \
    @wdio/local-runner@^7.16.16 \
    @wdio/selenium-standalone-service@^7.16.16 \
    @wdio/spec-reporter@^7.16.14 \
    axios@^0.26.0 \
    browserstack-local@^1.4.8 \
    fs-extra@^10.0.1 \
    global-agent@^3.0.0 \
    multiple-cucumber-html-reporter@^1.19.0 \
    wdio-cucumber-reporter@0.0.2 \
    wdio-cucumberjs-json-reporter@^4.4.0 \
    wdio-json-reporter@^3.0.0 \
    wdio-image-comparison-service@^3.1.0 \
    -q --ignore-scripts \
    && mkdir testOutput \
    && mkdir -p wdio/reports

Using a node 14 image as base image.a

**Error log during docker run:**
> payment-plans-online@0.0.0-gitversion test-browserstack-cb-wdio /app
> TEST_TYPE=crossBrowser wdio run wdio/config/wdio.crossBrowser.conf.js


Execution of 5 workers started at 2022-04-02T23:47:49.132Z

2022-04-02T23:47:49.210Z ERROR @wdio/utils:initialiseServices: Error: Couldn't initialise "wdio-image-comparison-service".
Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- /app/node_modules/canvas/lib/bindings.js
- /app/node_modules/canvas/lib/canvas.js
- /app/node_modules/canvas/index.js
- /app/node_modules/webdriver-image-comparison/build/resemble/resemble.js
- /app/node_modules/webdriver-image-comparison/build/resemble/compareImages.js
- /app/node_modules/webdriver-image-comparison/build/methods/images.js
- /app/node_modules/webdriver-image-comparison/build/commands/saveScreen.js
- /app/node_modules/wdio-image-comparison-service/build/service.js
- /app/node_modules/wdio-image-comparison-service/build/index.js
- /app/node_modules/@wdio/utils/build/utils.js
- /app/node_modules/@wdio/utils/build/initialisePlugin.js
- /app/node_modules/@wdio/utils/build/index.js
- /app/node_modules/@wdio/cli/build/launcher.js
- /app/node_modules/@wdio/cli/build/index.js
- /app/node_modules/@wdio/cli/bin/wdio.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module._compile (/app/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.newLoader [as .js] (/app/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at safeRequire (/app/node_modules/@wdio/utils/build/utils.js:192:15)
    at initialisePlugin (/app/node_modules/@wdio/utils/build/initialisePlugin.js:37:44)
    at initialiseServices (/app/node_modules/@wdio/utils/build/initialiseServices.js:59:56)
    at initialiseLauncherService (/app/node_modules/@wdio/utils/build/initialiseServices.js:86:26)
    at Launcher.run (/app/node_modules/@wdio/cli/build/launcher.js:73:103)
    at launch (/app/node_modules/@wdio/cli/build/commands/run.js:126:21)
    at Object.handler (/app/node_modules/@wdio/cli/build/commands/run.js:164:16)
    at /app/node_modules/yargs/build/index.cjs:1:9054
    at j (/app/node_modules/yargs/build/index.cjs:1:4931)
    at M.applyMiddlewareAndGetResult (/app/node_modules/yargs/build/index.cjs:1:9023)
2022-04-02T23:47:49.244Z INFO @wdio/cli:launcher: Run onPrepare hook
Connecting local

**Comment by wswebcreation** [comment]
I've upgraded the canvas lib to the latest version, can you check the latest version https://github.com/wswebcreation/wdio-image-comparison-service/releases/tag/v3.1.1

**Comment by wbigno** [comment]
Upgraded version to 3.1.1 i can see it in my node_modules
+-- wdio-image-comparison-service@3.1.1
| +-- @wdio/logger@7.19.0 deduped
| `-- webdriver-image-comparison@0.20.3
|   +-- canvas@2.9.1
|   | +-- @mapbox/node-pre-gyp@1.0.9
|   | | +-- detect-libc@2.0.1
|   | | +-- https-proxy-agent@5.0.0 deduped
|   | | +-- make-dir@3.1.0
|   | | | `-- semver@6.3.0
|   | | +-- node-fetch@2.6.7 deduped
|   | | +-- nopt@5.0.0
|   | | | `-- abbrev@1.1.1
|   | | +-- npmlog@5.0.1
|   | | | +-- are-we-there-yet@2.0.0
|   | | | | +-- delegates@1.0.0
|   | | | | `-- readable-stream@3.6.0 deduped
|   | | | +-- console-control-strings@1.1.0
|   | | | +-- gauge@3.0.2
|   | | | | +-- aproba@2.0.0
|   | | | | +-- color-support@1.1.3
|   | | | | +-- console-control-strings@1.1.0 deduped
|   | | | | +-- has-unicode@2.0.1
|   | | | | +-- object-assign@4.1.1 deduped
|   | | | | +-- signal-exit@3.0.7 deduped
|   | | | | +-- string-width@4.2.3 deduped
|   | | | | +-- strip-ansi@6.0.1 deduped
|   | | | | `-- wide-align@1.1.5
|   | | | |   `-- string-width@4.2.3 deduped
|   | | | `-- set-blocking@2.0.0
|   | | +-- rimraf@3.0.2 deduped
|   | | +-- semver@7.3.5
|   | | | `-- lru-cache@6.0.0
|   | | |   `-- yallist@4.0.0
|   | | `-- tar@6.1.11
|   | |   +-- chownr@2.0.0
|   | |   +-- fs-minipass@2.1.0
|   | |   | `-- minipass@3.1.6 deduped
|   | |   +-- minipass@3.1.6
|   | |   | `-- yallist@4.0.0
|   | |   +-- minizlib@2.1.2
|   | |   | +-- minipass@3.1.6 deduped
|   | |   | `-- yallist@4.0.0
|   | |   +-- mkdirp@1.0.4 deduped
|   | |   `-- yallist@4.0.0
|   | +-- nan@2.15.0
|   | `-- simple-get@3.1.1
|   |   +-- decompress-response@4.2.1
|   |   | `-- mimic-response@2.1.0
|   |   +-- once@1.4.0 deduped
|   |   `-- simple-concat@1.0.1
|   +-- chalk@4.1.2
|   | +-- ansi-styles@4.3.0
|   | | `-- color-convert@2.0.1
|   | |   `-- color-name@1.1.4
|   | `-- supports-color@7.2.0
|   |   `-- has-flag@4.0.0
|   `-- fs-extra@10.0.1 deduped

Here is my updated package.json
"devDependencies": {
    "@babel/cli": "^7.17.6",
    "@babel/core": "^7.17.5",
    "@babel/preset-env": "^7.16.11",
    "@babel/register": "^7.17.0",
    "@babel/eslint-parser": "^7.17.0",
    "@wdio/allure-reporter": "^7.17.3",
    "@wdio/cli": "^7.17.4",
    "@wdio/devtools-service": "^7.17.4",
    "@wdio/junit-reporter": "^7.17.3",
    "@wdio/local-runner": "^7.17.4",
    "@wdio/mocha-framework": "^7.17.3",
    "@wdio/sauce-service": "^7.17.4",
    "@wdio/spec-reporter": "^7.17.3",
    "@wdio/sync": "^7.17.4",
    "wdio-image-comparison-service": "^3.1.1",
    "webdriverio": "^6.4.0",
    "allure-commandline": "^2.13.0",
    "chai": "^4.2.0",
    "chai-html": "^1.3.0",
    "chai-match-pattern": "^1.2.0",
    "chromedriver": "^99.0.0",
    "eslint": "^8.10.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-babel": "^5.3.1",
    "eslint-plugin-mocha": "^6.3.0",
    "global-agent": "^2.1.12",
    "request-promise": "^4.2.6",
    "request": "^2.34.0",
    "request-promise-core": "^1.1.4",
    "xml2js": "^0.4.23"
  }

but I am still seeing the same error in my logs

2022-04-04T17:29:32.841Z DEBUG @wdio/utils:initialiseServices: initialise service "sauce" as NPM package
2022-04-04T17:29:33.095Z DEBUG @wdio/utils:initialiseServices: initialise service "image-comparison" as NPM package
2022-04-04T17:29:33.124Z ERROR @wdio/utils:initialiseServices: Error: Couldn't initialise "wdio-image-comparison-service".
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/canvas/build/Release/canvas.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader [as .js] (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/pirates/lib/index.js:141:7)
    at safeRequire (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/@wdio/utils/build/utils.js:192:15)
    at initialisePlugin (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/@wdio/utils/build/initialisePlugin.js:37:44)
    at initialiseServices (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/@wdio/utils/build/initialiseServices.js:59:56)
    at initialiseLauncherService (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/@wdio/utils/build/initialiseServices.js:86:26)
    at Launcher.run (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/@wdio/cli/build/launcher.js:73:103)
    at launch (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/@wdio/cli/build/commands/run.js:126:21)
    at Object.handler (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/@wdio/cli/build/commands/run.js:164:16)
    at /prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/yargs/build/index.cjs:1:9054
    at j (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/yargs/build/index.cjs:1:4931)
    at M.applyMiddlewareAndGetResult (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/yargs/build/index.cjs:1:9023)
2022-04-04T17:29:33.157Z INFO @wdio/cli:launcher: Run onPrepare hook
2022-04-04T17:29:33.160Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-04-04T17:29:33.160Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-04-04T17:29:33.160Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-04-04T17:29:33.160Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-04-04T17:29:33.162Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,wdio.saucelabs.chrome.conf.js,--suite,nyl_beta_analytics
2022-04-04T17:29:33.177Z INFO @wdio/local-runner: Start worker 0-1 with arg: run,wdio.saucelabs.chrome.conf.js,--suite,nyl_beta_analytics
2022-04-04T17:29:33.186Z INFO @wdio/local-runner: Start worker 0-2 with arg: run,wdio.saucelabs.chrome.conf.js,--suite,nyl_beta_analytics
2022-04-04T17:29:33.194Z INFO @wdio/local-runner: Start worker 0-3 with arg: run,wdio.saucelabs.chrome.conf.js,--suite,nyl_beta_analytics
2022-04-04T17:29:36.212Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code null
2022-04-04T17:29:36.213Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2022-04-04T17:29:36.224Z DEBUG @wdio/local-runner: Runner 0-1 finished with exit code null
2022-04-04T17:29:36.225Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2022-04-04T17:29:36.226Z DEBUG @wdio/local-runner: Runner 0-3 finished with exit code null
2022-04-04T17:29:36.226Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2022-04-04T17:29:36.231Z DEBUG @wdio/local-runner: Runner 0-2 finished with exit code null
2022-04-04T17:29:36.232Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2022-04-04T17:29:36.232Z INFO @wdio/cli:launcher: Run onComplete hook
2022-04-04T17:29:36.255Z INFO @wdio/local-runner: Shutting down spawned worker
2022-04-04T17:29:36.506Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully

**Comment by gulatirajat** [comment]
**Similar error on my side as well:**
2022-04-05T01:21:56.830Z ERROR @wdio/utils:initialiseServices: Error: Couldn't initialise "wdio-image-comparison-service".
Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- /app/node_modules/canvas/lib/bindings.js
- /app/node_modules/canvas/lib/canvas.js
- /app/node_modules/canvas/index.js
- /app/node_modules/webdriver-image-comparison/build/resemble/resemble.js
- /app/node_modules/webdriver-image-comparison/build/resemble/compareImages.js
- /app/node_modules/webdriver-image-comparison/build/methods/images.js
- /app/node_modules/webdriver-image-comparison/build/commands/saveScreen.js
- /app/node_modules/wdio-image-comparison-service/build/service.js
- /app/node_modules/wdio-image-comparison-service/build/index.js
- /app/node_modules/@wdio/utils/build/utils.js
- /app/node_modules/@wdio/utils/build/initialisePlugin.js
- /app/node_modules/@wdio/utils/build/index.js
- /app/node_modules/@wdio/cli/build/launcher.js
- /app/node_modules/@wdio/cli/build/index.js
- /app/node_modules/@wdio/cli/bin/wdio.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/app/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/app/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader [as .js] (/app/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at safeRequire (/app/node_modules/@wdio/utils/build/utils.js:192:15)
    at initialisePlugin (/app/node_modules/@wdio/utils/build/initialisePlugin.js:37:44)
    at initialiseServices (/app/node_modules/@wdio/utils/build/initialiseServices.js:59:56)
    at initialiseLauncherService (/app/node_modules/@wdio/utils/build/initialiseServices.js:86:26)
    at Launcher.run (/app/node_modules/@wdio/cli/build/launcher.js:73:103)
    at launch (/app/node_modules/@wdio/cli/build/commands/run.js:126:21)
    at Object.handler (/app/node_modules/@wdio/cli/build/commands/run.js:164:16)
    at /app/node_modules/yargs/build/index.cjs:1:9054
    at j (/app/node_modules/yargs/build/index.cjs:1:4931)
    at M.applyMiddlewareAndGetResult (/app/node_modules/yargs/build/index.cjs:1:9023)
2022-04-05T01:21:56.858Z INFO @wdio/cli:launcher: Run onPrepare hook

**From inside the docker container:**
$ npm list wdio-image-comparison-service
payment-plans-online@0.0.0-gitversion /app
`-- wdio-image-comparison-service@3.1.1 

$ node -v
v14.19.1
$

**Comment by wswebcreation** [comment]
hmm,

Still seems to be an environmental issue. You might want to look into the docs of [node-canvas](https://github.com/Automattic/node-canvas/wiki/_pages) and check the steps you need to follow / dependencies you might need to add to your (docker) container to make this work. 
By default it should work an provide prebuild binaries for a lot of standard platforms

**Comment by wbigno** [comment]
Wim

I am now getting the same build error on my local win10 machine which was building and running without any issues on the prior version. 

It’s running v14 and has not had any issues until I updated the version to 3.1.1 yesterday. 

Not sure if that helps, thanks

**Comment by gulatirajat** [comment]
After some digging in and changes to the docker file being used to build the wdio image, I was able to resolve it for docker container (running on my local mac machine). Now it downloads this package from within the docker container and installs:
https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v83-linux-glibc-x64.tar.gz

However since there are restrictions on our corporate enterprise jenkins on what can be downloaded from external git, I run into such errors:
08:52:50  > canvas@2.9.1 install /app/node_modules/canvas
08:52:50  > node-pre-gyp install --fallback-to-build
08:52:50  
08:52:50  node-pre-gyp ERR! install response status 403 Forbidden on https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v83-linux-glibc-x64.tar.gz 
08:52:50  node-pre-gyp WARN Pre-built binaries not installable for canvas@2.9.1 and node@14.19.1 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
08:52:50  node-pre-gyp WARN Hit error response status 403 Forbidden on https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v83-linux-glibc-x64.tar.gz 
08:52:52  /bin/sh: 1: pkg-config: not found
08:52:52  gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
08:52:52  gyp ERR! configure error 
08:52:52  gyp ERR! stack Error: `gyp` failed with exit code: 1
08:52:52  gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
08:52:52  gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
08:52:52  gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
08:52:52  gyp ERR! System Linux 5.10.106-102.504.amzn2.x86_64
08:52:52  gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/app/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/app/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
08:52:52  gyp ERR! cwd /app/node_modules/canvas
08:52:52  gyp ERR! node -v v14.19.1
08:52:52  gyp ERR! node-gyp -v v5.1.0
08:52:52  gyp ERR! not ok 
08:52:52  node-pre-gyp ERR! build error 
08:52:52  node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/app/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
08:52:52  node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/app/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
08:52:52  node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
08:52:52  node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
08:52:52  node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
08:52:52  node-pre-gyp ERR! System Linux 5.10.106-102.504.amzn2.x86_64
08:52:52  node-pre-gyp ERR! command "/usr/bin/node" "/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
08:52:52  node-pre-gyp ERR! cwd /app/node_modules/canvas
08:52:52  node-pre-gyp ERR! node -v v14.19.1
08:52:52  node-pre-gyp ERR! node-pre-gyp -v v1.0.9
08:52:52  node-pre-gyp ERR! not ok 

Is there a way to build the core wdio-image-comparison-service package in a way so that such dependencies are managed/resolved as part of the package and hence avoids download.

**Comment by wswebcreation** [comment]
Hi @wbigno 

Due to the 403 it tries to build it itself and it might be that your docker image doesn't have the correct dependencies. Can you check if you have all of these https://github.com/Automattic/node-canvas#compiling?

**Comment by wswebcreation** [comment]
Closing this one due to inactivity, feel free to re-open or create a new issue if this still happens
